services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    platform: linux/amd64
    container_name: nestjs
    ports:
      - "3001:3000"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - postgres
  postgres:
    image: postgres:13.22-alpine
    platform: linux/amd64
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  db-store:
